#!/bin/bash
path=$1
outputtag=$2

# Default to current directory if no directory is given.
if [[ "$path"X == X ]]; then
    path=`pwd` # Use `pwd` instead of '.' so that the $outputtag gets a good value if not provided by the user.
fi

if [[ "$path" == "." ]]; then
    path=`pwd`
fi

# If the path exists, create the feedback/output directory.
if [ -d "$path" ]; then
    mkdir -p "$path/feedback/output"
else # If the path doesn't exist, exit.
    echo "Path doesn't exist."
    exit 1
fi

# Default to using the parent folder for tag if none is given.
if [[ "$outputtag"X == X ]]; then
    outputtag=`basename "$path" | sed 's/ /_/g'`
fi

outputtag="$outputtag"_feedback

# Find all the files that are likely to be student submissions, and try to avoid any of the files that probably aren't.
find "$path" -maxdepth 1 \! -name "feedback" \! -name "Makefile" \! -name "index.html" \! -name "*.md" \! -name ".*" | while read file; do
    # Get the name of the student.
    student_name=`echo $file | awk -F"- " '{print $2}' | sed -e 's/^ //g' | sed '/%$/d' | sed 's/ /_/g'`

    if [ ${#student_name} -eq 0 ]; then
        continue
    fi

    
    # Get the base name of the file.
    base_filename=`basename "$file"`

    filetype=`file -b "$file"`

    unique_id=`echo $base_filename | awk '{print $1}'`
    
    case "$filetype" in
        Zip*)
            echo "Unzipping $file..."
            unzip -q -d "${file//.zip/}" "$file"
            rm "$file"
            ;;
    esac

    out_basename="$unique_id"_"$student_name"_"$outputtag".md
    
    #echo $student_name generated from $file.

    # If there is not an existing Markdown file for the submission, create one.
    # Should avoid overwriting any existing feedback files (would suck to lose
    # your work...)
    if [ ! -f "$path/feedback/$out_basename" -a ! -f "$path/$out_basename" ]; then
        echo "Creating empty Markdown template for $student_name."

        # Create the markdown file, initialized with a header containing the student's name.
        echo "# $student_name" > "$path/$out_basename"
    fi
done

